### ISSUE TITLE
Hard coded symptoms, drugs and triggers

### ISSUE THREAD

**Issue by kianilannoye** [kianilannoye/Chronicals#14]
The hard coded symptoms, drugs and triggers all have an "id" field in the object, but this needs to be replaced to the name as it is stored in the database (check datamodel.jpg)

Also: the hardcoded stuff needs to be replaced by a database call (most of them are already present in comment lines)

for example: 
a drug could be defined as:
{drugID:1, name: "naam van de drug", description: "beschrijving van de drug"}

I already tried to do this, but somewhere in the code of the views, the field "id" is referenced, which does not exist anymore.

**Comment by GillesVandewiele** [comment]
Write DAO in dataservice instead of changing all variable names etc
