### ISSUE TITLE
MobileApp : dashboard open : retrieve drugslist, triggerlist and symptomslist

### ISSUE THREAD

**Issue by kianilannoye** [kianilannoye/Chronicals#17]
Retrieve the information needed in the app and concat with the current items in the dataService.

Also, if a user logged in, retrieve the newest version of patient object from the database and store the information in the database. The patient object is returned when making the login call. Catch this and store the data.

Not needed when user just registered

**Comment by GillesVandewiele** [comment]
get advice as well

**Comment by GillesVandewiele** [comment]
Not bugging today? I remember it did bug yesterday??!! Anyway.. closed for now
